/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user: building and roles */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /** Forget me: building, roles and the link to my tickets */
        delete: operations["forget_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/demo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo buildings to choose from (in real life the QR picks it) */
        get: operations["demo_buildings_api_v1_buildings_demo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/residency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Bind me to a building */
        put: operations["bind_residency_api_v1_me_residency_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/demo-dispatcher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DEMO_MODE only: become a dispatcher of the demo management company */
        post: operations["become_demo_dispatcher_api_v1_me_demo_dispatcher_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/building": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My building: pulse for 30 days and the QR leaflet */
        get: operations["my_building_api_v1_me_building_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings/{building_id}/leaflet.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Printable leaflet with a QR code to the bot; the link is signed */
        get: operations["leaflet_api_v1_buildings__building_id__leaflet_pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My tickets */
        get: operations["list_my_tickets_api_v1_tickets_get"];
        put?: never;
        /** Register the resident's ticket from the confirmed draft */
        post: operations["create_ticket_api_v1_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dispatcher/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dispatcher queue: open tickets first, by deadline */
        get: operations["dispatcher_queue_api_v1_dispatcher_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket card */
        get: operations["get_ticket_api_v1_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatcher moves the ticket; the resident gets a notification */
        post: operations["change_status_api_v1_tickets__ticket_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reporter confirms the fix or reopens the ticket */
        post: operations["confirm_api_v1_tickets__ticket_id__confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/escalation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reporter asks for a complaint to the housing inspection; the bot sends the PDF to the reporter's chat */
        post: operations["escalate_api_v1_tickets__ticket_id__escalation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/demo/expire-deadline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** DEMO_MODE only: move the reporter's deadline into the past, so the overdue notice and the complaint can be checked without waiting */
        post: operations["demo_expire_deadline_api_v1_tickets__ticket_id__demo_expire_deadline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Next clarifying question, or the draft with category and deadline */
        post: operations["analyze_api_v1_intake_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deadline after the resident answered whether it is an emergency */
        post: operations["preview_api_v1_intake_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/intake/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit the draft by the resident's remark */
        post: operations["refine_api_v1_intake_refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quick categories with the first clarifying question; 'other' is last */
        get: operations["categories_api_v1_reference_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/responsibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who answers for what around a building, and where to turn */
        get: operations["responsibility_api_v1_reference_responsibility_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorRole
         * @description Who performs an action on a ticket.
         * @enum {string}
         */
        ActorRole: "resident" | "dispatcher" | "system";
        /** AnalyzeIn */
        AnalyzeIn: {
            /** Turns */
            turns: components["schemas"]["TurnIn"][];
            /**
             * Category Code
             * @description Quick category the resident picked, if any
             */
            category_code?: string | null;
        };
        /** BuildingOut */
        BuildingOut: {
            /** Code */
            code: string;
            /** Address */
            address: string;
        };
        /** CategoryCountOut */
        CategoryCountOut: {
            /** Category Code */
            category_code: string;
            /** Count */
            count: number;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Code */
            code: string;
            /** Emoji */
            emoji: string;
            /** Title */
            title: string;
            /** Clarifying Question */
            clarifying_question: string;
        };
        /** ConfirmationIn */
        ConfirmationIn: {
            /**
             * Resolved
             * @description true: problem fixed; false: reopen the ticket
             */
            resolved: boolean;
            /** Comment */
            comment?: string | null;
        };
        /** DispatcherOut */
        DispatcherOut: {
            /**
             * Company Id
             * Format: uuid
             */
            company_id: string;
            /** Company Name */
            company_name: string;
        };
        /** DraftStepOut */
        DraftStepOut: {
            /**
             * Ready
             * @description true: `draft` and `triage` are set
             */
            ready: boolean;
            /** Explanation */
            explanation: string;
            /** Question */
            question: string | null;
            /** Draft */
            draft: string | null;
            triage: components["schemas"]["TriageOut"] | null;
        };
        /** ForgetOut */
        ForgetOut: {
            /**
             * Detached Tickets
             * @description Tickets that lost the link to the user
             */
            detached_tickets: number;
        };
        /** GuideEntryOut */
        GuideEntryOut: {
            /** Emoji */
            emoji: string;
            /** Situation */
            situation: string;
            party: components["schemas"]["ResponsibleParty"] | null;
            /** Who */
            who: string;
            /** Basis */
            basis: string;
            /** Where */
            where: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HouseOut */
        HouseOut: {
            /** Building Code */
            building_code: string;
            /** Address */
            address: string;
            /** Company Name */
            company_name: string;
            /** Company Phone */
            company_phone: string;
            pulse: components["schemas"]["PulseOut"];
            /**
             * Leaflet Path
             * @description Signed path of the printable QR leaflet (PDF), no auth header needed: MAX `downloadFile` cannot send one
             */
            leaflet_path: string;
            /** Leaflet Filename */
            leaflet_filename: string;
        };
        /** MeOut */
        MeOut: {
            /** Max User Id */
            max_user_id: number;
            residency: components["schemas"]["ResidencyOut"] | null;
            dispatcher: components["schemas"]["DispatcherOut"] | null;
            /** Demo Mode */
            demo_mode: boolean;
        };
        /** PreviewIn */
        PreviewIn: {
            /** Category Code */
            category_code: string;
            /** Is Emergency */
            is_emergency: boolean;
        };
        /** PulseOut */
        PulseOut: {
            /** Period Days */
            period_days: number;
            /** Total */
            total: number;
            /** Open */
            open: number;
            /** Overdue */
            overdue: number;
            /** Fixed */
            fixed: number;
            /** Fixed On Time */
            fixed_on_time: number;
            /**
             * On Time Share
             * @description 0..1, null when nothing fixed
             */
            on_time_share: number | null;
            /** Average Fix Hours */
            average_fix_hours: number | null;
            /** Top Categories */
            top_categories: components["schemas"]["CategoryCountOut"][];
            /** Neighbours Joined */
            neighbours_joined: number;
        };
        /** RefineIn */
        RefineIn: {
            /** Draft */
            draft: string;
            /** Comment */
            comment: string;
        };
        /** RefineOut */
        RefineOut: {
            /** Draft */
            draft: string;
        };
        /** ResidencyIn */
        ResidencyIn: {
            /**
             * Building Code
             * @description Code from the QR in the entrance
             */
            building_code: string;
        };
        /** ResidencyOut */
        ResidencyOut: {
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Building Code */
            building_code: string;
            /** Address */
            address: string;
            /** Company Name */
            company_name: string;
            /** Company Phone */
            company_phone: string;
        };
        /**
         * ResponsibleParty
         * @description Organisation that is legally responsible for fixing the problem.
         * @enum {string}
         */
        ResponsibleParty: "management_company" | "resource_supplier" | "capital_repair_operator" | "municipality" | "owner";
        /** StatusChangeIn */
        StatusChangeIn: {
            /**
             * Status
             * @enum {string}
             */
            status: "acknowledged" | "in_progress" | "done" | "rejected";
            /** Comment */
            comment?: string | null;
        };
        /** TicketCreateIn */
        TicketCreateIn: {
            /** Category Code */
            category_code: string;
            /** Is Emergency */
            is_emergency: boolean;
            /** Description */
            description: string;
        };
        /** TicketEventOut */
        TicketEventOut: {
            status: components["schemas"]["TicketStatus"];
            actor_role: components["schemas"]["ActorRole"];
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Comment */
            comment: string | null;
        };
        /** TicketOut */
        TicketOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Building Address */
            building_address: string;
            /** Category Code */
            category_code: string;
            /** Is Emergency */
            is_emergency: boolean;
            /** Description */
            description: string;
            responsible_party: components["schemas"]["ResponsibleParty"];
            /** Responsibility Basis */
            responsibility_basis: string;
            status: components["schemas"]["TicketStatus"];
            /**
             * Resolve By
             * Format: date-time
             */
            resolve_by: string;
            /** React By */
            react_by: string | null;
            /** Deadline Basis */
            deadline_basis: string;
            /** Is Overdue */
            is_overdue: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Events */
            events: components["schemas"]["TicketEventOut"][];
            /**
             * Available Statuses
             * @description Statuses the current user may move this ticket to
             */
            available_statuses: components["schemas"]["TicketStatus"][];
            /**
             * Escalated At
             * @description When the reporter asked for a complaint to the housing inspection
             */
            escalated_at: string | null;
            /**
             * Can Escalate
             * @description The current user (the reporter) may ask for the complaint now
             */
            can_escalate: boolean;
            /**
             * Can Confirm
             * @description The current user (the reporter) may confirm or reopen now
             */
            can_confirm: boolean;
            /**
             * Supporters Count
             * @description Neighbours who pressed "me too" in the house chat
             */
            supporters_count: number;
            /**
             * From House Chat
             * @description Filed from a house chat card
             */
            from_house_chat: boolean;
            /**
             * Photo Urls
             * @description Photos the resident attached
             */
            photo_urls: string[];
            /**
             * Demo Can Expire
             * @description DEMO_MODE: the reporter may move the deadline into the past
             */
            demo_can_expire: boolean;
        };
        /**
         * TicketStatus
         * @description Lifecycle of a ticket. Allowed moves live in `state_machine.py`.
         * @enum {string}
         */
        TicketStatus: "registered" | "acknowledged" | "in_progress" | "done" | "confirmed" | "rejected";
        /** TriageOut */
        TriageOut: {
            /** Category Code */
            category_code: string;
            /** Is Emergency */
            is_emergency: boolean;
            /**
             * Needs Emergency Confirmation
             * @description The classifier is unsure: ask the resident whether it is an emergency, then call /intake/preview with the answer
             */
            needs_emergency_confirmation: boolean;
            responsible_party: components["schemas"]["ResponsibleParty"];
            /** Responsibility Basis */
            responsibility_basis: string;
            /**
             * Resolve By
             * Format: date-time
             */
            resolve_by: string;
            /** React By */
            react_by: string | null;
            /** Deadline Basis */
            deadline_basis: string;
        };
        /** TurnIn */
        TurnIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "bot";
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_buildings_api_v1_buildings_demo_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_residency_api_v1_me_residency_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResidencyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    become_demo_dispatcher_api_v1_me_demo_dispatcher_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_building_api_v1_me_building_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HouseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaflet_api_v1_buildings__building_id__leaflet_pdf_get: {
        parameters: {
            query: {
                sig: string;
            };
            header?: never;
            path: {
                building_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_tickets_api_v1_tickets_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ticket_api_v1_tickets_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dispatcher_queue_api_v1_dispatcher_queue_get: {
        parameters: {
            query?: {
                include_closed?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_v1_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_status_api_v1_tickets__ticket_id__status_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_tickets__ticket_id__confirmation_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_api_v1_tickets__ticket_id__escalation_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demo_expire_deadline_api_v1_tickets__ticket_id__demo_expire_deadline_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_intake_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftStepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_intake_preview_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_api_v1_intake_refine_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefineIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefineOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    categories_api_v1_reference_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    responsibility_api_v1_reference_responsibility_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuideEntryOut"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
